# Versión eliminada para evitar warnings

services:
  mongodb:
    image: mongo:5.0
    container_name: flores-victoria-dev-mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - database-network
      - flores-victoria-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: flores-victoria-dev-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    networks:
      - flores-victoria-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:7-alpine
    container_name: flores-victoria-dev-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_dev_data:/data
    networks:
      - flores-victoria-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:14-alpine
    container_name: flores-victoria-dev-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - flores-victoria-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Exporters para monitoreo
  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: flores-victoria--mongodb-exporter
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
    ports:
      - "9216:9216"
    networks:
      - flores-victoria-network
    depends_on:
      - mongodb

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: flores-victoria--postgres-exporter
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - flores-victoria-network
    depends_on:
      - postgres

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: flores-victoria--redis-exporter
    env_file:
      - .env
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "9121:9121"
    networks:
      - flores-victoria-network
    depends_on:
      - redis

  # Panel de administración
  admin-panel:
    image: flores-victoria--admin-panel
    container_name: flores-victoria--admin-panel
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env
    environment:
      PORT: 3010
      MONGO_URI: ${ADMIN_PANEL_MONGODB_URI}
    networks:
      - flores-victoria-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3010/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s