global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3003']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3004']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3005']

  - job_name: 'wishlist-service'
    static_configs:
      - targets: ['wishlist-service:3006']

  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service:3007']

  - job_name: 'contact-service'
    static_configs:
      - targets: ['contact-service:3008']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics