FROM node:16-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Crear directorio para Vite y dar permisos
RUN mkdir -p /app/node_modules/.vite
RUN chown -R node:node /app
RUN chmod -R 777 /app/node_modules

# Cambiar a usuario node para evitar problemas de permisos
USER node

# Exponer puerto de desarrollo
EXPOSE 5173

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]