version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: 
      context: ./microservices/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./microservices/api-gateway:/app
      - /app/node_modules
    env_file:
      - ./microservices/.env
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - auth-service
      - product-service

  # Authentication Service
  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./microservices/auth-service:/app
      - /app/node_modules
    env_file:
      - ./microservices/.env
    environment:
      - NODE_ENV=development
      - PORT=3001

  # Product Service
  product-service:
    build:
      context: ./microservices/product-service
      dockerfile: Dockerfile.dev
    ports:
      - "3009:3009"
    volumes:
      - ./microservices/product-service:/app
      - ./shared:/shared
      - /app/node_modules
    env_file:
      - ./microservices/.env
    environment:
      - NODE_ENV=development
      - PORT=3009

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./microservices/.env
    environment:
      - NODE_ENV=development

  # Admin Panel
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    volumes:
      - ./admin-panel:/app
      - /app/node_modules
    env_file:
      - ./microservices/.env
    environment:
      - NODE_ENV=development