version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: 
      context: ./microservices/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./microservices/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - auth-service
      - product-service

  # Authentication Service
  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./microservices/auth-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=your-super-secret-jwt-key
      - LOGGING_SERVICE_URL=http://logging-service:3005

  # Product Service
  product-service:
    build:
      context: ./microservices/product-service
      dockerfile: Dockerfile.dev
    ports:
      - "3009:3009"
    volumes:
      - ./microservices/product-service:/app
      - ./shared:/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3009
      - LOGGING_SERVICE_URL=http://logging-service:3005
      - CACHE_SERVICE_URL=http://redis:6379
    depends_on:
      - redis
      - logging-service

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Logging Service
  logging-service:
    build:
      context: ./microservices/logging-service
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3005"
    volumes:
      - ./microservices/logging-service:/app
      - ./microservices/logging-service/logs:/app/logs
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3005

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # Admin Panel
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    volumes:
      - ./admin-panel:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development