
FROM node:18

WORKDIR /app

# Copiar shared y su package-lock.json (dependencia local)
COPY ../shared ./node_modules/@flores-victoria/shared
COPY ../shared/package-lock.json ./node_modules/@flores-victoria/shared/package-lock.json

# Copiar archivos de configuración del servicio
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código de la aplicación
COPY src/ ./src/

# Exponer puerto
EXPOSE 3000

# Comando para ejecutar la aplicación en modo desarrollo
CMD ["npm", "run", "dev"]