FROM node:18

WORKDIR /app

# Copiar directorio shared primero
COPY shared/ ./shared/

# Copiar archivos de configuración del servicio
COPY api-gateway/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código de la aplicación
COPY api-gateway/src/ ./src/

# Exponer puerto
EXPOSE 3000

# Comando para ejecutar la aplicación en modo desarrollo
CMD ["npm", "run", "dev"]