# Configuración de alertas para Grafana
apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: 'Alerts'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/alerts