apiVersion: v1
kind: ConfigMap
metadata:
  name: flores-victoria-config
  namespace: {{ .Values.namespace }}
data:
  # Database configurations
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  
  # Redis configurations
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  
  # MongoDB configurations
  MONGO_HOST: {{ .Values.config.mongoHost | quote }}
  MONGO_PORT: {{ .Values.config.mongoPort | quote }}
  
  # RabbitMQ configurations
  RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.config.rabbitmqPort | quote }}
  
  # Jaeger configurations
  JAEGER_HOST: {{ .Values.config.jaegerHost | quote }}
  JAEGER_PORT: {{ .Values.config.jaegerPort | quote }}
  
  # Service ports
  AUTH_SERVICE_PORT: {{ .Values.config.authServicePort | quote }}
  USER_SERVICE_PORT: {{ .Values.config.userServicePort | quote }}
  PRODUCT_SERVICE_PORT: {{ .Values.config.productServicePort | quote }}
  ORDER_SERVICE_PORT: {{ .Values.config.orderServicePort | quote }}
  CART_SERVICE_PORT: {{ .Values.config.cartServicePort | quote }}
  WISHLIST_SERVICE_PORT: {{ .Values.config.wishlistServicePort | quote }}
  REVIEW_SERVICE_PORT: {{ .Values.config.reviewServicePort | quote }}
  CONTACT_SERVICE_PORT: {{ .Values.config.contactServicePort | quote }}
  API_GATEWAY_PORT: {{ .Values.config.apiGatewayPort | quote }}
  ADMIN_PANEL_PORT: {{ .Values.config.adminPanelPort | quote }}