global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    cluster: 'flores-victoria-prod'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-service'
    static_configs:
      - targets: ['172.17.0.1:4013']
    metrics_path: '/metrics'

  - job_name: 'order-service'
    static_configs:
      - targets: ['172.17.0.1:4004']
    metrics_path: '/metrics'

  - job_name: 'admin-panel'
    static_configs:
      - targets: ['172.17.0.1:4021']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['172.17.0.1:4016']
    metrics_path: '/metrics'
