FROM node:18

WORKDIR /app

# Copiar package.json y package-lock.json si existe
COPY package*.json ./

# Instalar dependencias
RUN npm install --legacy-peer-deps


# Copiar código fuente excepto el directorio shared
COPY src/ src/

# Crear directorio de logs si no existe
RUN mkdir -p logs

EXPOSE 3009

# Establecer el puerto en el entorno
ENV PORT=3009

CMD ["npm", "run", "dev"]