apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: flores-victoria
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: flores-victoria--auth-service
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: flores-victoria-config
            - secretRef:
                name: flores-victoria-secrets
          env:
            - name: PORT
              value: "3001"
            - name: DB_PATH
              value: "/app/database.sqlite"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: flores-victoria-secrets
                  key: jwt_secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: flores-victoria
  labels:
    app: auth-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: auth-service