# ADVERTENCIA: Este archivo contiene secretos de ejemplo codificados en base64.
# En un entorno de producción, utilice secretos gestionados por el proveedor de nube
# o herramientas como HashiCorp Vault en lugar de codificar secretos directamente.

apiVersion: v1
kind: Secret
metadata:
  name: flores-victoria-secrets
  namespace: flores-victoria
type: Opaque
data:
  # Valores codificados en base64
  # echo -n "your-jwt-secret-here" | base64
  jwt_secret: eW91ci1qd3Qtc2VjcmV0LWhlcmU=
  # echo -n "your-mongo-root-password" | base64
  mongo_root_password: eW91ci1tb25nby1yb290LXBhc3N3b3Jk
  # echo -n "your-postgres-password" | base64
  postgres_password: eW91ci1wb3N0Z3Jlcy1wYXNzd29yZA==
  # echo -n "your-rabbitmq-password" | base64
  rabbitmq_password: eW91ci1yYWJiaXRtcS1wYXNzd29yZA==
  # echo -n "your-email-password" | base64
  email_password: eW91ci1lbWFpbC1wYXNzd29yZA==