FROM node:16-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Crear directorio para Vite y dar permisos
RUN mkdir -p /app/node_modules/.vite
RUN chown -R node:node /app

# Cambiar a usuario node para evitar problemas de permisos
USER node

# Establecer el puerto
ENV PORT=3010

# Exponer puerto de desarrollo
EXPOSE 3010

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]