---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: flores-victoria
  labels:
    app: api-gateway
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: api-gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: flores-victoria
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: floresvictoria/api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:4001"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
            - name: USER_SERVICE_URL
              value: "http://user-service:3003"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3004"
            - name: CART_SERVICE_URL
              value: "http://cart-service:3005"
            - name: WISHLIST_SERVICE_URL
              value: "http://wishlist-service:3006"
            - name: REVIEW_SERVICE_URL
              value: "http://review-service:3007"
            - name: CONTACT_SERVICE_URL
              value: "http://contact-service:3008"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5