---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
  namespace: flores-victoria
  labels:
    app: contact-service
spec:
  ports:
    - port: 3008
      targetPort: 3008
  selector:
    app: contact-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-service
  namespace: flores-victoria
  labels:
    app: contact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-service
  template:
    metadata:
      labels:
        app: contact-service
    spec:
      containers:
        - name: contact-service
          image: floresvictoria/contact-service:latest
          ports:
            - containerPort: 3008
          env:
            - name: PORT
              value: "3008"
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: DB_NAME
              value: "flores_db"
            - name: DB_PORT
              value: "5432"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3008
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3008
            initialDelaySeconds: 5
            periodSeconds: 5