---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: flores-victoria
  labels:
    app: product-service
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: product-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: flores-victoria
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: floresvictoria/product-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: DB_HOST
              value: "mongodb"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mongo-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mongo-password
            - name: DB_NAME
              value: "products"
            - name: DB_PORT
              value: "27017"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5