---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: flores-victoria
  labels:
    app: review-service
spec:
  ports:
    - port: 3007
      targetPort: 3007
  selector:
    app: review-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: flores-victoria
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: floresvictoria/review-service:latest
          ports:
            - containerPort: 3007
          env:
            - name: PORT
              value: "3007"
            - name: DB_HOST
              value: "mongodb"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mongo-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mongo-password
            - name: DB_NAME
              value: "reviews"
            - name: DB_PORT
              value: "27017"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 5
            periodSeconds: 5