---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: flores-victoria
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: localhost:5000/microservices_api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3001"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
            - name: USER_SERVICE_URL
              value: "http://user-service:3003"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3004"
            - name: CART_SERVICE_URL
              value: "http://cart-service:3005"
            - name: WISHLIST_SERVICE_URL
              value: "http://wishlist-service:3006"
            - name: REVIEW_SERVICE_URL
              value: "http://review-service:3007"
            - name: CONTACT_SERVICE_URL
              value: "http://contact-service:3008"
            - name: RABBITMQ_URL
              value: "amqp://admin:adminpassword@rabbitmq:5672"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5