---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: flores-victoria
  labels:
    app: auth-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: auth-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: microservices_auth-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
          volumeMounts:
            - name: auth-db-storage
              mountPath: /app/db
      volumes:
        - name: auth-db-storage
          persistentVolumeClaim:
            claimName: auth-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: flores-victoria
  labels:
    app: product-service
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: product-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: microservices_product-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
              # Esta configuración debe mejorarse en producción
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: flores-victoria
  labels:
    app: user-service
spec:
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: microservices_user-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          livenessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: flores-victoria
  labels:
    app: order-service
spec:
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: order-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: microservices_order-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          livenessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: flores-victoria
  labels:
    app: cart-service
spec:
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: cart-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: microservices_cart-service:latest
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: flores-victoria
  labels:
    app: wishlist-service
spec:
  ports:
    - port: 3006
      targetPort: 3006
  selector:
    app: wishlist-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
        - name: wishlist-service
          image: microservices_wishlist-service:latest
          ports:
            - containerPort: 3006
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /
              port: 3006
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3006
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: flores-victoria
  labels:
    app: review-service
spec:
  ports:
    - port: 3007
      targetPort: 3007
  selector:
    app: review-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: microservices_review-service:latest
          ports:
            - containerPort: 3007
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              value: "mongodb://root:rootpassword@mongodb:27017/reviews_db?authSource=admin"
          livenessProbe:
            httpGet:
              path: /
              port: 3007
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3007
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
  namespace: flores-victoria
  labels:
    app: contact-service
spec:
  ports:
    - port: 3008
      targetPort: 3008
  selector:
    app: contact-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-service
  namespace: flores-victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-service
  template:
    metadata:
      labels:
        app: contact-service
    spec:
      containers:
        - name: contact-service
          image: microservices_contact-service:latest
          ports:
            - containerPort: 3008
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              value: "mongodb://root:rootpassword@mongodb:27017/contactdb?authSource=admin"
            - name: EMAIL_HOST
              value: "smtp.gmail.com"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_SECURE
              value: "false"
            - name: EMAIL_USER
              value: "tu_email@gmail.com"
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email-password
          livenessProbe:
            httpGet:
              path: /
              port: 3008
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3008
            initialDelaySeconds: 5
            periodSeconds: 5