name: Health Check Services

on:
  schedule:
    # Ejecutar cada 30 minutos / Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Permite ejecución manual / Allow manual execution

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check MCP Server Health
        run: |
          curl -f http://your-mcp-server:5050/health || echo "⚠️ MCP Server no disponible"
        continue-on-error: true

      - name: Check All Services and Create Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -f "http://your-mcp-server:5050/check-services?createIssues=true" || echo "⚠️ No se pudo verificar servicios"
        continue-on-error: true

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Health Check Fallido / Health Check Failed',
              body: 'El health check programado ha fallado. Revisar logs del workflow.\n\nThe scheduled health check has failed. Check workflow logs.',
              labels: ['bug', 'high-priority', 'monitoring']
            });
