# Validación automática de enlaces en documentación

name: Markdown Link Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      - name: Run markdown-link-check on all .md files
        run: |
          find . -name "*.md" | xargs -I {} markdown-link-check -c .github/markdown-link-check-config.json {}